In [28]:
import numpy as np
import pandas as pd
import pennylane as qml
from susy_qm import calculate_Hamiltonian
from susy_qm import calculate_wz_hamiltonian

In [32]:
psi = np.array([1/2, 1/2, 1/2, 1/2])
psi = np.array([1/np.sqrt(2), 0, 0, 1/np.sqrt(2)])

psi_matrix = psi.reshape(2, 2)
print(psi_matrix)

U, s, Vh = np.linalg.svd(psi_matrix, full_matrices=False)
print(U)
print(s)
print(Vh)

p = s**2

print(p)
entropy = -np.sum(p[p > 0] * np.log(p[p > 0]))
print("Entanglement entropy:", entropy)


[[0.70710678 0.        ]
 [0.         0.70710678]]
[[1. 0.]
 [0. 1.]]
[0.70710678 0.70710678]
[[1. 0.]
 [0. 1.]]
[0.5 0.5]
Entanglement entropy: 0.6931471805599453


In [11]:
potential = 'DW'
cutoff = 4

In [12]:
#calculate Hamiltonian and expected eigenvalues
H = calculate_Hamiltonian(cutoff, potential)

eigenvalues, eigenvectors = np.linalg.eig(H)
min_index = np.argmin(eigenvalues)
min_eigenvalue = eigenvalues[min_index]
min_eigenvector = np.asarray(eigenvectors[:, min_index])

min_3_ev = eigenvalues.argsort()[:3]

In [14]:
eig_vec = np.asarray(eigenvectors[:, min_3_ev[0]])
mat = eig_vec.reshape(2,cutoff)

u, s, vh = np.linalg.svd(mat, full_matrices=False)
print(U)
print(s)
print(Vh)
p = s**2

entropy = -np.sum(p[p > 0] * np.log(p[p > 0]))
print("Entanglement entropy:", entropy)

[[1. 0.]
 [0. 1.]]
[1. 0.]
[[1. 0.]
 [0. 1.]]
Entanglement entropy: -0.0


In [15]:
eig_vec

array([ 0.        +0.j,  0.        +0.j,  0.        +0.j,  0.        +0.j,
        0.96698015+0.j, -0.16164595+0.j, -0.18805279+0.j,  0.05878883+0.j])

In [16]:
mat

array([[ 0.        +0.j,  0.        +0.j,  0.        +0.j,
         0.        +0.j],
       [ 0.96698015+0.j, -0.16164595+0.j, -0.18805279+0.j,
         0.05878883+0.j]])

In [6]:
cutoff_list = [2,4,8,16]
potential_list = ['QHO', 'DW', 'AHO']

for potential in potential_list:
    for cutoff in cutoff_list:

        H = calculate_Hamiltonian(cutoff, potential)

        eigenvalues, eigenvectors = np.linalg.eig(H)
        min_index = np.argmin(eigenvalues)
        min_eigenvalue = eigenvalues[min_index]
        min_eigenvector = np.asarray(eigenvectors[:, min_index])

        min_3_ev = eigenvalues.argsort()[:3]

        for e_lev in range(3):
            eig_vec = np.asarray(eigenvectors[:, min_3_ev[e_lev]])
            mat = eig_vec.reshape(2,cutoff)

            u, s, vh = np.linalg.svd(mat, full_matrices=False)
            p = s**2

            p = p / np.sum(p)

            entropy = -np.sum(p[p > 0] * np.log(p[p > 0]))
            print("Entanglement entropy:", entropy)


Entanglement entropy: -0.0
Entanglement entropy: -0.0
Entanglement entropy: -0.0
Entanglement entropy: -0.0
Entanglement entropy: -0.0
Entanglement entropy: -0.0
Entanglement entropy: -0.0
Entanglement entropy: -0.0
Entanglement entropy: -0.0
Entanglement entropy: -0.0
Entanglement entropy: -0.0
Entanglement entropy: -0.0
Entanglement entropy: -0.0
Entanglement entropy: -0.0
Entanglement entropy: -0.0
Entanglement entropy: -0.0
Entanglement entropy: -0.0
Entanglement entropy: -0.0
Entanglement entropy: -0.0
Entanglement entropy: -0.0
Entanglement entropy: -0.0
Entanglement entropy: -0.0
Entanglement entropy: -0.0
Entanglement entropy: -0.0
Entanglement entropy: -0.0
Entanglement entropy: -0.0
Entanglement entropy: -0.0
Entanglement entropy: -0.0
Entanglement entropy: -0.0
Entanglement entropy: -0.0
Entanglement entropy: -0.0
Entanglement entropy: -0.0
Entanglement entropy: -0.0
Entanglement entropy: 2.1941600293002325e-31
Entanglement entropy: -0.0
Entanglement entropy: -0.0


In [12]:
a = 1.0
sites = [2,3]
potential_list = ['linear', 'quadratic']
bc_list = ['periodic', 'dirichlet']
cutoff_list = [2,4]

d_bcs = []
d_potentials = []
d_sites = []
d_cutoff = []
d_entropies = []

for boundary_condition in bc_list:
    for potential in potential_list:
        for N in sites:
            for cutoff in cutoff_list:

                if potential == 'linear':
                    c=0
                else:
                    c=-0.8
                print(cutoff, N, a, potential, boundary_condition, c)
                H = calculate_wz_hamiltonian(cutoff, N, a, potential, boundary_condition, c)
                eigenvalues, eigenvectors = np.linalg.eig(H)
                min_index = np.argmin(eigenvalues)
                min_eigenvalue = eigenvalues[min_index]
                min_eigenvector = np.asarray(eigenvectors[:, min_index])

                min_3_ev = eigenvalues.argsort()[:3]

                entropies = []

                for e_lev in range(3):
                    eig_vec = np.asarray(eigenvectors[:, min_3_ev[e_lev]])
                    mat = eig_vec.reshape([2,cutoff]*N)

                    u, s, vh = np.linalg.svd(mat, full_matrices=False)
                    p = s**2

                    p = p / np.sum(p)

                    entropy = -np.sum(p[p > 0] * np.log2(p[p > 0]))
                    #print("Entanglement entropy:", entropy)
                    entropies.append(entropy)

                d_bcs.append(boundary_condition)
                d_potentials.append(potential)
                d_sites.append(N)
                d_cutoff.append(cutoff)
                d_entropies.append(entropies)

2 2 1.0 linear periodic 0
4 2 1.0 linear periodic 0
2 3 1.0 linear periodic 0
4 3 1.0 linear periodic 0
2 2 1.0 quadratic periodic -0.8
4 2 1.0 quadratic periodic -0.8
2 3 1.0 quadratic periodic -0.8
4 3 1.0 quadratic periodic -0.8
2 2 1.0 linear dirichlet 0
4 2 1.0 linear dirichlet 0
2 3 1.0 linear dirichlet 0
4 3 1.0 linear dirichlet 0
2 2 1.0 quadratic dirichlet -0.8
4 2 1.0 quadratic dirichlet -0.8
2 3 1.0 quadratic dirichlet -0.8
4 3 1.0 quadratic dirichlet -0.8


In [14]:
data = {'boundary_condition': d_bcs,
        'potential': d_potentials,
        'sites': d_sites,
        'cutoff': d_cutoff,
        'entropies': d_entropies}

df = pd.DataFrame(data)
df[['e1', 'e2', 'e3']] = pd.DataFrame(df['entropies'].tolist(), index=df.index)

In [15]:
df

boundary_condition  potential  sites  cutoff  \
0            periodic     linear      2       2   
1            periodic     linear      2       4   
2            periodic     linear      3       2   
3            periodic     linear      3       4   
4            periodic  quadratic      2       2   
5            periodic  quadratic      2       4   
6            periodic  quadratic      3       2   
7            periodic  quadratic      3       4   
8           dirichlet     linear      2       2   
9           dirichlet     linear      2       4   
10          dirichlet     linear      3       2   
11          dirichlet     linear      3       4   
12          dirichlet  quadratic      2       2   
13          dirichlet  quadratic      2       4   
14          dirichlet  quadratic      3       2   
15          dirichlet  quadratic      3       4   

                                            entropies            e1  \
0                                  [-0.0, -0.0, -0.0] -0.000000e+00   
1   [1.2024318819340826e-30, 2.1931380874042616e-2...  1.202432e-30   
2   [2.7103871772509045, 2.710387177250904, 2.4560...  2.710387e+00   
3   [0.5590080945457092, 1.1971900597256897, 2.981...  5.590081e-01   
4         [2.0, 2.0053359415580108, 2.08326203729745]  2.000000e+00   
5   [1.6437761230259733, 1.7815863374539782, 1.615...  1.643776e+00   
6   [3.5315784240908865, 3.5292636683183494, 4.057...  3.531578e+00   
7   [5.590174196349956, 5.584215791039318, 5.00571...  5.590174e+00   
8   [0.2981175133945634, 0.2981175133945634, 0.298...  2.981175e-01   
9   [0.0331432326523854, 1.01692749232054, 1.01659...  3.314323e-02   
10  [1.542300388914758, 1.538546173824912, 1.53404...  1.542300e+00   
11  [0.36918695040676813, 2.2392708256662504, 1.32...  3.691870e-01   
12       [2.0, 2.889021133674177, 2.9042831836107617]  2.000000e+00   
13  [2.8656437053039143, 2.103627307115309, 3.0780...  2.865644e+00   
14  [3.69876222153453, 3.7115034791278267, 3.20414...  3.698762e+00   
15  [5.337577521429422, 5.220133015065876, 4.37949...  5.337578e+00   

              e2            e3  
0  -0.000000e+00 -0.000000e+00  
1   2.193138e-28  4.460943e-30  
2   2.710387e+00  2.456034e+00  
3   1.197190e+00  2.981627e+00  
4   2.005336e+00  2.083262e+00  
5   1.781586e+00  1.615653e+00  
6   3.529264e+00  4.057390e+00  
7   5.584216e+00  5.005714e+00  
8   2.981175e-01  2.981175e-01  
9   1.016927e+00  1.016598e+00  
10  1.538546e+00  1.534042e+00  
11  2.239271e+00  1.324336e+00  
12  2.889021e+00  2.904283e+00  
13  2.103627e+00  3.078046e+00  
14  3.711503e+00  3.204140e+00  
15  5.220133e+00  4.379493e+00

In [ ]:
df

boundary_condition  potential  sites  cutoff  \
0            periodic     linear      2       2   
1            periodic     linear      2       4   
2            periodic     linear      3       2   
3            periodic     linear      3       4   
4            periodic  quadratic      2       2   
5            periodic  quadratic      2       4   
6            periodic  quadratic      3       2   
7            periodic  quadratic      3       4   
8           dirichlet     linear      2       2   
9           dirichlet     linear      2       4   
10          dirichlet     linear      3       2   
11          dirichlet     linear      3       4   
12          dirichlet  quadratic      2       2   
13          dirichlet  quadratic      2       4   
14          dirichlet  quadratic      3       2   
15          dirichlet  quadratic      3       4   

                                            entropies            e1  \
0                                  [-0.0, -0.0, -0.0] -0.000000e+00   
1   [1.2024318819340826e-30, 2.1931380874042616e-2...  1.202432e-30   
2   [2.7103871772509045, 2.710387177250904, 2.4560...  2.710387e+00   
3   [0.5590080945457092, 1.1971900597256897, 2.981...  5.590081e-01   
4         [2.0, 2.038115177672391, 2.046277972888269]  2.000000e+00   
5   [1.8006959494115375, 1.8007058882413596, 1.234...  1.800696e+00   
6   [3.5315784240908865, 3.5292636683183494, 4.057...  3.531578e+00   
7   [2.456201536691243, 2.60549497275534, 4.220334...  2.456202e+00   
8   [0.2981175133945634, 0.2981175133945634, 0.298...  2.981175e-01   
9   [0.0331432326523854, 1.01692749232054, 1.01659...  3.314323e-02   
10  [1.542300388914758, 1.538546173824912, 1.53404...  1.542300e+00   
11  [0.36918695040676813, 2.2392708256662504, 1.32...  3.691870e-01   
12      [2.0, 2.9134558843273775, 2.8916764854218258]  2.000000e+00   
13  [1.1889329985069166, 1.834387789651543, 1.3483...  1.188933e+00   
14  [3.4751023719586347, 3.625096675740223, 3.1850...  3.475102e+00   
15  [2.776527570077222, 2.663973880200712, 5.01387...  2.776528e+00   

              e2            e3  
0  -0.000000e+00 -0.000000e+00  
1   2.193138e-28  4.460943e-30  
2   2.710387e+00  2.456034e+00  
3   1.197190e+00  2.981627e+00  
4   2.038115e+00  2.046278e+00  
5   1.800706e+00  1.234782e+00  
6   3.529264e+00  4.057390e+00  
7   2.605495e+00  4.220335e+00  
8   2.981175e-01  2.981175e-01  
9   1.016927e+00  1.016598e+00  
10  1.538546e+00  1.534042e+00  
11  2.239271e+00  1.324336e+00  
12  2.913456e+00  2.891676e+00  
13  1.834388e+00  1.348374e+00  
14  3.625097e+00  3.185038e+00  
15  2.663974e+00  5.013874e+00

In [ ]:
H = calculate_wz_hamiltonian(cutoff, N, a, potential, boundary_condition, c)
    
eigenvalues, eigenvectors = np.linalg.eig(H)
min_index = np.argmin(eigenvalues)
min_eigenvalue = eigenvalues[min_index]
min_eigenvector = np.asarray(eigenvectors[:, min_index])

In [ ]:
# Parameters
N = 2
a = 1.0
c = -0.2
potential = 'quadratic'
potential = 'linear'
boundary_condition = 'dirichlet'
#boundary_condition = 'periodic'

cutoff=4

In [ ]:
#mat = min_eigenvector.reshape(2, 2, 2, 2, 2, 2)
#mat = min_eigenvector.reshape(4,4,4)
#mat = min_eigenvector.reshape(4,16)
mat = min_eigenvector.reshape([2,4]*N)
mat

In [ ]:
u, s, vh = np.linalg.svd(mat, full_matrices=False)
p = s**2

p = p / np.sum(p)

entropy = -np.sum(p[p > 0] * np.log2(p[p > 0]))
print("Entanglement entropy:", entropy)