In [1]:
# PennyLane imports
import pennylane as qml
from pennylane import numpy as pnp

from scipy.optimize import differential_evolution
from scipy.sparse.linalg import eigsh

# General imports
import os
import json
import numpy as np
from datetime import datetime

from qiskit.quantum_info import SparsePauliOp

from scipy.stats.qmc import Halton

# custom module
from susy_qm import calculate_wz_hamiltonian

In [11]:
# Parameters
N = 2
a = 1.0
c = -0.8
potential = 'quadratic'#"linear"#
boundary_condition = 'dirichlet'
#boundary_condition = 'periodic'
cutoff = 2

In [12]:
cutoffs = [2,4,8,16]
for cutoff in cutoffs:
    print(cutoff, N, a, potential, boundary_condition, c)
    H = calculate_wz_hamiltonian(cutoff, N, a, potential, boundary_condition, c)
        
    eigenvalues, eigenvectors = np.linalg.eig(H)
    min_eigenvalue = min(eigenvalues.real)
    min_index = np.argmin(eigenvalues)
    min_eigenvalue = eigenvalues[min_index]
    min_eigenvector = np.asarray(eigenvectors[:, min_index])

    num_levels = 1
    min_ev = eigenvalues.argsort()[:num_levels]
    for e_lev in range(num_levels):
        eig_vec = np.asarray(eigenvectors[:, min_ev[e_lev]].real)
        eig_vec[np.abs(eig_vec) < 1e-9] = 0
        eig_vec = eig_vec.reshape((cutoff**N, 2**N))
        print(eig_vec)
        print("#####################################")

2 2 1.0 quadratic dirichlet -0.8
[[ 0.   0.   0.  -0.5]
 [ 0.   0.   0.  -0.5]
 [ 0.   0.   0.   0.5]
 [ 0.   0.   0.   0.5]]
#####################################
4 2 1.0 quadratic dirichlet -0.8
[[ 0.12361458  0.          0.          0.        ]
 [-0.17991837  0.          0.          0.        ]
 [ 0.18245416  0.          0.          0.        ]
 [-0.16012159  0.          0.          0.        ]
 [ 0.17991837  0.          0.          0.        ]
 [-0.29767427  0.          0.          0.        ]
 [ 0.32021741  0.          0.          0.        ]
 [-0.27123488  0.          0.          0.        ]
 [ 0.18245416  0.          0.          0.        ]
 [-0.32021741  0.          0.          0.        ]
 [ 0.35320783  0.          0.          0.        ]
 [-0.29592679  0.          0.          0.        ]
 [ 0.16012159  0.          0.          0.        ]
 [-0.27123488  0.          0.          0.        ]
 [ 0.29592679  0.          0.          0.        ]
 [-0.24778044  0.          0.         

array([[ 0.5,  0. ,  0. ,  0. ],
       [-0.5,  0. ,  0. ,  0. ],
       [ 0.5,  0. ,  0. ,  0. ],
       [-0.5,  0. ,  0. ,  0. ]])